
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {AntdRegistry} from "@ant-design/nextjs-registry"
import MainContextProvider from "./context";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { QueryProvider } from "./query";
import Header from "./_mycomponents/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new  QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <MainContextProvider>
            <AntdRegistry>
              <Header />
              <div className="lg:px-16 md:px-10 px-7 lg:py-10 md:py-8 py-6 bg-yellow-50">
                <div className="max-w-[1150px] min-h-[100vh] mx-auto">
                  {children}
                </div>
                  
              </div>
            </AntdRegistry>
          </MainContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
