
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry"
import MainContextProvider from "./context";
import Header from "./_mycomponents/header";
import { ReactQueryProvider } from "./components/reactQuery";
import { ConfigProvider } from "antd";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainContextProvider>
      <AntdRegistry>
        <ConfigProvider theme={{hashed: true}}>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <ReactQueryProvider>
                <Header />
                <div className="lg:px-16 md:px-10 px-7 lg:py-10 md:py-8 py-6 bg-yellow-50">
                  <div className="max-w-[1150px] min-h-[100vh] mx-auto">
                    {children}
                  </div>
                </div>
            </ReactQueryProvider>
          </body>
        </html>
        </ConfigProvider>
      </AntdRegistry>
    </MainContextProvider>
  );
}
